#!/bin/zsh
BACKUP_SRC_DIR=""
BACKUP_DEST_DIR=""
RSYNC_FLAGS="-avz --delete --exclude '.DS_Store'"
rsync $RSYNC_FLAGS $BACKUP_SRC_DIR/Desktop/ $BACKUP_DEST_DIR/Desktop
rsync $RSYNC_FLAGS $BACKUP_SRC_DIR/Documents/ $BACKUP_DEST_DIR/Documents
rsync $RSYNC_FLAGS $BACKUP_SRC_DIR/Movies/ $BACKUP_DEST_DIR/Movies
rsync $RSYNC_FLAGS $BACKUP_SRC_DIR/Music/ $BACKUP_DEST_DIR/Music
rsync $RSYNC_FLAGS $BACKUP_SRC_DIR/Pictures/ $BACKUP_DEST_DIR/Pictures
